/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.MoveJFrame;
import Model.ManipularImagem;
import Model.TratamentoUpload;
import DAO.SalvarImagemDAO;
import Model.Usuario;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author Caio Henrique
 */


public class TelaInicial extends MoveJFrame {

    //Inicializações
    private ImageIcon iconBotao;
    private ImageIcon backgroundAlbum;
    private CardLayout cardLayout;
    private BufferedImage image;
    private ImageIcon img;
    private ManipularImagem manipularImagem = new ManipularImagem();
    private JFileChooser ImagemUpload = new JFileChooser();
    private List listaFotos;
    int pagina = 0;
    private int res;
    
    
    
   
    
    public TelaInicial() throws SQLException, IOException {
        initComponents();
        //Definindo O Layout dos Paines
        cardLayout = (CardLayout)(paineis.getLayout());
        //Buscando o nome do usuario logado
        nomeUsuario.setText(Usuario.getName());
     
        //Buscando a Primeira foto do usuario
        this.listaFotos = SalvarImagemDAO.recuperarImagemIds(Usuario.getId(), Usuario.pasta);
        fixarCodigo.setSelected(true);
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        painel_menu = new javax.swing.JPanel();
        btnSobre = new javax.swing.JButton();
        btnUpload1 = new javax.swing.JButton();
        nomeUsuario = new javax.swing.JLabel();
        paineis = new javax.swing.JPanel();
        painel_Upload = new javax.swing.JPanel();
        btnSelecionar = new javax.swing.JButton();
        painelImagemSelecionar = new javax.swing.JPanel();
        caminhoImagem = new javax.swing.JTextField();
        nomeParaCodificar = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        nomeEmCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fixarCodigo = new javax.swing.JCheckBox();
        btnCodificar = new javax.swing.JButton();
        painel_Sobre = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        btnminimizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setEnabled(false);

        painel_menu.setBackground(new java.awt.Color(0, 51, 255));

        btnSobre.setBackground(new java.awt.Color(0, 51, 255));
        btnSobre.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnSobre.setForeground(new java.awt.Color(255, 255, 255));
        btnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sobreMenu.png"))); // NOI18N
        btnSobre.setText("              Sobre  ");
        btnSobre.setAlignmentX(0.5F);
        btnSobre.setBorder(null);
        btnSobre.setContentAreaFilled(false);
        btnSobre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSobre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSobre.setOpaque(true);
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSobreMouseExited(evt);
            }
        });
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });

        btnUpload1.setBackground(new java.awt.Color(0, 51, 255));
        btnUpload1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnUpload1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpload1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/uploadMenu.png"))); // NOI18N
        btnUpload1.setText("           Upload  ");
        btnUpload1.setAlignmentY(0.0F);
        btnUpload1.setBorder(null);
        btnUpload1.setContentAreaFilled(false);
        btnUpload1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnUpload1.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnUpload1.setOpaque(true);
        btnUpload1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpload1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpload1MouseExited(evt);
            }
        });
        btnUpload1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpload1ActionPerformed(evt);
            }
        });

        nomeUsuario.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        nomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeUsuario.setText("Usuario");
        nomeUsuario.setToolTipText("");

        javax.swing.GroupLayout painel_menuLayout = new javax.swing.GroupLayout(painel_menu);
        painel_menu.setLayout(painel_menuLayout);
        painel_menuLayout.setHorizontalGroup(
            painel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUpload1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painel_menuLayout.setVerticalGroup(
            painel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_menuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnUpload1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(painel_menu);

        paineis.setLayout(new java.awt.CardLayout());

        painel_Upload.setBackground(new java.awt.Color(255, 255, 255));

        btnSelecionar.setBackground(new java.awt.Color(0, 51, 255));
        btnSelecionar.setFont(new java.awt.Font("Sylfaen", 0, 11)); // NOI18N
        btnSelecionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/selecionar.png"))); // NOI18N
        btnSelecionar.setContentAreaFilled(false);
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        painelImagemSelecionar.setOpaque(false);
        painelImagemSelecionar.setPreferredSize(new java.awt.Dimension(760, 402));

        caminhoImagem.setEditable(false);
        caminhoImagem.setBackground(new java.awt.Color(0, 51, 255));
        caminhoImagem.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        caminhoImagem.setForeground(new java.awt.Color(255, 255, 255));
        caminhoImagem.setText(" /...");
        caminhoImagem.setToolTipText("");
        caminhoImagem.setBorder(null);
        caminhoImagem.setMargin(new java.awt.Insets(0, 5, 0, 0));
        caminhoImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoImagemActionPerformed(evt);
            }
        });

        nomeParaCodificar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        nomeParaCodificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSalvar.setBackground(new java.awt.Color(0, 51, 255));
        btnSalvar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/uploadMenu.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        nomeEmCodigo.setEditable(false);
        nomeEmCodigo.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        nomeEmCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeEmCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmCodigoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setText("Nome :");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel2.setText("Codigo :");

        fixarCodigo.setText("Fixa Codigo");
        fixarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixarCodigoActionPerformed(evt);
            }
        });

        btnCodificar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnCodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/criptografar.png"))); // NOI18N
        btnCodificar.setText("Criptografar");
        btnCodificar.setBorder(null);
        btnCodificar.setContentAreaFilled(false);
        btnCodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_UploadLayout = new javax.swing.GroupLayout(painel_Upload);
        painel_Upload.setLayout(painel_UploadLayout);
        painel_UploadLayout.setHorizontalGroup(
            painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_UploadLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_UploadLayout.createSequentialGroup()
                        .addComponent(nomeParaCodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCodificar)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(painel_UploadLayout.createSequentialGroup()
                        .addGroup(painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painel_UploadLayout.createSequentialGroup()
                                .addGroup(painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(caminhoImagem)
                                    .addComponent(painelImagemSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                                    .addComponent(fixarCodigo))
                                .addGap(18, 18, 18))
                            .addGroup(painel_UploadLayout.createSequentialGroup()
                                .addComponent(nomeEmCodigo)
                                .addGap(28, 28, 28)))
                        .addGroup(painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_UploadLayout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addGap(82, 82, 82))))))
        );
        painel_UploadLayout.setVerticalGroup(
            painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_UploadLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_UploadLayout.createSequentialGroup()
                        .addComponent(caminhoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelImagemSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeParaCodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnCodificar))
                .addGap(17, 17, 17)
                .addGroup(painel_UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fixarCodigo)
                .addGap(24, 24, 24))
        );

        paineis.add(painel_Upload, "painel_Upload");
        painel_Upload.getAccessibleContext().setAccessibleName("painel_Upload");

        painel_Sobre.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel4.setText("Bruno Bueno Cunha");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel6.setText("Caio Henrique");

        jLabel8.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel8.setText("Cássio Ferreira Machado");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel9.setText("Esse Software foi desenvolvido para a realização do projeto do primeiro semestre do curso de Ciência da computação ,");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel10.setText("pela Universidade Nove de Julho , onde é abordados os seguinte requisitos :");

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel11.setText("Linguagem de programação Java.");

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel12.setText("Conceito de Design.");

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel13.setText("UML.");

        jLabel14.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel14.setText("Fernando Berlato Francisco");

        jLabel15.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel15.setText("Modelagem e desenvolvimento de software.");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setText("Photo Security");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setText("Software desenvolvido por :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel16.setText("Guilherme Santos Alboz");

        jLabel17.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel17.setText("Gustavo Siqueira Pires");

        jLabel18.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel18.setText("Gustavo Bispo Duarte");

        jLabel19.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel19.setText("Mapeamento de Negocio.");

        javax.swing.GroupLayout painel_SobreLayout = new javax.swing.GroupLayout(painel_Sobre);
        painel_Sobre.setLayout(painel_SobreLayout);
        painel_SobreLayout.setHorizontalGroup(
            painel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painel_SobreLayout.createSequentialGroup()
                .addGroup(painel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_SobreLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(painel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19)))
                    .addGroup(painel_SobreLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(painel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(445, Short.MAX_VALUE))
        );
        painel_SobreLayout.setVerticalGroup(
            painel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_SobreLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        paineis.add(painel_Sobre, "painel_Sobre");
        painel_Sobre.getAccessibleContext().setAccessibleName("painel_Sobre");

        jSplitPane1.setRightComponent(paineis);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSair.setText("X");
        btnSair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSair.setContentAreaFilled(false);
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnMaximizar.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        btnMaximizar.setText("|_|");
        btnMaximizar.setBorder(null);
        btnMaximizar.setContentAreaFilled(false);
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseExited(evt);
            }
        });
        btnMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizarActionPerformed(evt);
            }
        });

        btnminimizar.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        btnminimizar.setText("___");
        btnminimizar.setBorder(null);
        btnminimizar.setContentAreaFilled(false);
        btnminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnminimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnminimizarMouseExited(evt);
            }
        });
        btnminimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnminimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaximizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        //Selecionando o menu "Sobre"
        cardLayout.show(paineis, "painel_Sobre");
    }//GEN-LAST:event_btnSobreActionPerformed

    private void btnUpload1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpload1ActionPerformed
        //Selecionando o menu "Upload"
        cardLayout.show(paineis, "painel_Upload");
    }//GEN-LAST:event_btnUpload1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        //Botão Sair
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnUpload1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpload1MouseEntered
        //Efeito para o botão mudar de cor
        btnUpload1.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_btnUpload1MouseEntered

    private void btnUpload1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpload1MouseExited
        //Efeito para o botão mudar de cor
        btnUpload1.setBackground(new java.awt.Color(0,51,255));
    }//GEN-LAST:event_btnUpload1MouseExited

    private void btnSobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseEntered
        //Efeito para o botão mudar de cor
        btnSobre.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_btnSobreMouseEntered

    private void btnSobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseExited
        //Efeito para o botão mudar de cor
        btnSobre.setBackground(new java.awt.Color(0,51,255));
    }//GEN-LAST:event_btnSobreMouseExited

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
    //Botão Para Selecionar foto para ser feito o upload    
        //Removendo qualquer foto antes de abrir uma nova.
        painelImagemSelecionar.removeAll();
        //Filtrando extenção de arquivos JPG/PNG.
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens JPG/PNG", "jpg","png");
        ImagemUpload.addChoosableFileFilter(filtro);
        ImagemUpload.setAcceptAllFileFilterUsed(false);
        //Quardando o resultado da consulta da janela de seleção.
        this.res = ImagemUpload.showOpenDialog(null);
        
        //Verificando oque acontece com o JFikeChooser
        switch(res){
            case JFileChooser.CANCEL_OPTION:  //Caso o usuario cancele.
                break;
            case JFileChooser.APPROVE_OPTION: //Caso o usuario escolha um arquivo
                  //Adicionando a imagem no "painelImagemSelecionar".
                try {
                /**
                 * new Tratamento.Upload().selecionarImagem() Retorna a imagem selecionada ja redimencionada para o Preview_Upload.
                 * new Preview_Upload() Recebe a Imagem e desenha no background.
                 */
                caminhoImagem.setText(ImagemUpload.getCurrentDirectory().toString());
                 painelImagemSelecionar.add(new Preview_Upload(new TratamentoUpload().selecionarImagem(this.ImagemUpload , res))).revalidate();
            
            
                } catch (IOException | SQLException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            case JFileChooser.ERROR_OPTION:
                break;
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void caminhoImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caminhoImagemActionPerformed

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        //Efeito para o botão mudar de cor
        btnSair.setBackground(new java.awt.Color(240,194,3));
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        //Efeito para o botão mudar de cor 
        btnSair.setBackground(new java.awt.Color(10,2,195));
    }//GEN-LAST:event_btnSairMouseExited

    private void btnMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaximizarMouseEntered

    private void btnMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaximizarMouseExited

    private void btnMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizarActionPerformed
        //Botão para maximizar
        this.setLocation(0, 0);     
 
    }//GEN-LAST:event_btnMaximizarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
     //Salvando Imagem no banco de dados   
        
     switch(res){
         case JFileChooser.CANCEL_OPTION:
             break;
         case JFileChooser.APPROVE_OPTION:
                try {
                    if(!nomeEmCodigo.getText().isEmpty()){
                       if(new Usuario().uploadImagem(ImagemUpload , nomeParaCodificar.getText(),nomeEmCodigo.getText())){
                          //Apagando todo os registros depois de fazer upload
                           painelImagemSelecionar.removeAll(); 
                           painelImagemSelecionar.revalidate();
                           
                           if(!fixarCodigo.isSelected()){
                               nomeParaCodificar.setText("");
                               nomeEmCodigo.setText("");
                           }
                           caminhoImagem.setText(" /...");
                           cardLayout.show(paineis, "painel_Sobre");
                           cardLayout.show(paineis, "painel_Upload");
                           JOptionPane.showMessageDialog(this, "Imagem salva com sucesso!!!");
                       }else{
                           JOptionPane.showMessageDialog(this, "Erro");
                       }
                       //Atualizando a lista de fotos
                       this.listaFotos = SalvarImagemDAO.recuperarImagemIds(Usuario.getId(), Usuario.pasta);
                    }else{
                        JOptionPane.showMessageDialog(this, "Faltando codificação !");
                    }
                   } catch (IOException | SQLException ex ) {
                       Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                   }
                
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnminimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnminimizarMouseEntered

    private void btnminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnminimizarMouseExited

    private void btnminimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizarActionPerformed
        this.setState(TelaInicial.ICONIFIED);
    }//GEN-LAST:event_btnminimizarActionPerformed

    private void fixarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixarCodigoActionPerformed
       
    }//GEN-LAST:event_fixarCodigoActionPerformed

    private void btnCodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodificarActionPerformed
        if(nomeParaCodificar.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nome vazio");
            JOptionPane.showMessageDialog(this, fixarCodigo.isSelected());
            
        }else if(nomeParaCodificar.getText().contains(" ")){
            JOptionPane.showMessageDialog(this, "Nome Contem espaços");
        }else{
          
                nomeEmCodigo.setText(new Usuario().criptografandoSenha(nomeParaCodificar.getText()));
            
        };
      
    }//GEN-LAST:event_btnCodificarActionPerformed

    private void nomeEmCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaInicial().setVisible(true);
            } catch (SQLException | IOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCodificar;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnSobre;
    private javax.swing.JButton btnUpload1;
    private javax.swing.JButton btnminimizar;
    private javax.swing.JTextField caminhoImagem;
    private javax.swing.JCheckBox fixarCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField nomeEmCodigo;
    private javax.swing.JTextField nomeParaCodificar;
    private javax.swing.JLabel nomeUsuario;
    private javax.swing.JPanel paineis;
    private javax.swing.JPanel painelImagemSelecionar;
    private javax.swing.JPanel painel_Sobre;
    private javax.swing.JPanel painel_Upload;
    private javax.swing.JPanel painel_menu;
    // End of variables declaration//GEN-END:variables
}
